// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyFex.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyFex.Infrastructure.Migrations
{
    [DbContext(typeof(MoneyFexDbContext))]
    [Migration("20251129042632_AddTransactionIdempotencyKey")]
    partial class AddTransactionIdempotencyKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyFex.Core.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("banks", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.BankAccountDeposit", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("BankCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("BankId")
                        .HasColumnType("integer");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DuplicateTransactionReceiptNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HasMadePaymentToBankAccount")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBusiness")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEuropeTransfer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManualApprovalNeeded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManualDeposit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManuallyApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTransactionDuplicated")
                        .HasColumnType("boolean");

                    b.Property<string>("ReceiverAccountNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReceiverCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReceiverCountry")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ReceiverMobileNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId");

                    b.HasIndex("BankId");

                    b.HasIndex("RecipientId");

                    b.ToTable("bank_account_deposits", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.CardPaymentInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRecharged")
                        .HasColumnType("boolean");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CardTransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpiryDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsSavedCard")
                        .HasColumnType("boolean");

                    b.Property<string>("NameOnCard")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("NonCardTransactionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TopUpSomeoneElseTransactionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("TransferType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardTransactionId");

                    b.HasIndex("NonCardTransactionId");

                    b.HasIndex("TopUpSomeoneElseTransactionId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("TransferType");

                    b.ToTable("card_payment_information", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.CashPickup", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("AgentStaffName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApprovedByAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("MFCN")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("NonCardReceiverId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecipientIdentityCardId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipientIdentityCardNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId");

                    b.HasIndex("MFCN")
                        .IsUnique();

                    b.HasIndex("NonCardReceiverId");

                    b.HasIndex("RecipientId");

                    b.ToTable("cash_pickups", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CountryCode");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.KiiBankTransfer", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("AccountHolderPhoneNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AccountNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccountOwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BankBranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("BankBranchId")
                        .HasColumnType("integer");

                    b.Property<int?>("BankId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId");

                    b.HasIndex("BankId");

                    b.ToTable("kiibank_transfers", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.MobileMoneyTransfer", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaidToMobileNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReceiverCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WalletOperatorId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("WalletOperatorId");

                    b.ToTable("mobile_money_transfers", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.MobileWalletOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MobileNetworkCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PayoutProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("mobile_wallet_operators", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.ReceiverDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("receiver_details", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("recipients", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.ReinitializeTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NewReceiptNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("NewReceiptNo")
                        .IsUnique();

                    b.HasIndex("ReceiptNo");

                    b.ToTable("reinitialize_transactions", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.Sender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBusiness")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountNo")
                        .IsUnique();

                    b.HasIndex("CountryCode");

                    b.HasIndex("Email");

                    b.ToTable("senders", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.SenderLogin", b =>
                {
                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SenderId");

                    b.ToTable("sender_logins", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AgentCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("ApiService")
                        .HasColumnType("integer");

                    b.Property<int?>("CardProcessorApi")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ComplianceApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ComplianceApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExtraFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsComplianceApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplianceNeeded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFromMobile")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MFRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Margin")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("PayingStaffId")
                        .HasColumnType("integer");

                    b.Property<string>("PayingStaffName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<int?>("ReasonForTransfer")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ReceivingAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ReceivingCountryCode")
                        .IsRequired()
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ReceivingCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderPaymentMode")
                        .HasColumnType("integer");

                    b.Property<decimal>("SendingAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SendingCountryCode")
                        .IsRequired()
                        .HasColumnType("character varying(3)");

                    b.Property<string>("SendingCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionModule")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TransactionUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransferZeroSenderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByStaffId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceApprovedBy");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PayingStaffId");

                    b.HasIndex("PaymentReference");

                    b.HasIndex("ReceiptNo")
                        .IsUnique();

                    b.HasIndex("ReceivingCountryCode");

                    b.HasIndex("SenderId");

                    b.HasIndex("SendingCountryCode");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("UpdatedByStaffId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.Bank", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.BankAccountDeposit", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyFex.Core.Entities.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyFex.Core.Entities.Transaction", "Transaction")
                        .WithOne()
                        .HasForeignKey("MoneyFex.Core.Entities.BankAccountDeposit", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Recipient");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.CardPaymentInformation", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.CashPickup", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.ReceiverDetail", "NonCardReceiver")
                        .WithMany()
                        .HasForeignKey("NonCardReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyFex.Core.Entities.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyFex.Core.Entities.Transaction", "Transaction")
                        .WithOne()
                        .HasForeignKey("MoneyFex.Core.Entities.CashPickup", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NonCardReceiver");

                    b.Navigation("Recipient");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.KiiBankTransfer", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyFex.Core.Entities.Transaction", "Transaction")
                        .WithOne()
                        .HasForeignKey("MoneyFex.Core.Entities.KiiBankTransfer", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.MobileMoneyTransfer", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyFex.Core.Entities.Transaction", "Transaction")
                        .WithOne()
                        .HasForeignKey("MoneyFex.Core.Entities.MobileMoneyTransfer", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyFex.Core.Entities.MobileWalletOperator", "WalletOperator")
                        .WithMany()
                        .HasForeignKey("WalletOperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Transaction");

                    b.Navigation("WalletOperator");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.MobileWalletOperator", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.ReceiverDetail", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.ReinitializeTransaction", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Staff", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.Sender", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.SenderLogin", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Sender", "Sender")
                        .WithOne("Login")
                        .HasForeignKey("MoneyFex.Core.Entities.SenderLogin", "SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.Transaction", b =>
                {
                    b.HasOne("MoneyFex.Core.Entities.Staff", "ComplianceApprovedByStaff")
                        .WithMany()
                        .HasForeignKey("ComplianceApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyFex.Core.Entities.Staff", "PayingStaff")
                        .WithMany()
                        .HasForeignKey("PayingStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoneyFex.Core.Entities.Country", "ReceivingCountry")
                        .WithMany()
                        .HasForeignKey("ReceivingCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyFex.Core.Entities.Sender", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyFex.Core.Entities.Country", "SendingCountry")
                        .WithMany()
                        .HasForeignKey("SendingCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyFex.Core.Entities.Staff", "UpdatedByStaff")
                        .WithMany()
                        .HasForeignKey("UpdatedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ComplianceApprovedByStaff");

                    b.Navigation("PayingStaff");

                    b.Navigation("ReceivingCountry");

                    b.Navigation("Sender");

                    b.Navigation("SendingCountry");

                    b.Navigation("UpdatedByStaff");
                });

            modelBuilder.Entity("MoneyFex.Core.Entities.Sender", b =>
                {
                    b.Navigation("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
